#pragma once
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <strsafe.h>
#include <wlanapi.h>
#include <string>
#include <memory>
#include <list>
#include <unordered_map>
#include <functional>
#include "resource.h"
